### ISSUE TITLE
AFK time should be displayed in the user's TZ

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/xania#134]
When we fix #95 we should also fix `do_tell` to use the same display format.

**Comment by mattgodbolt** [comment]
Also maybe `do_time` in total (like Xania start time and systme time) in the user's TZ.

**Comment by snellers** [comment]
I've "fixed" this by simplifying Xania to only display times in UTC. The 'timezone' command no longer exists and help time mentions UTC too.
