### ISSUE TITLE
Signal handling code is clearly broken

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/xania#14]
There's very little one can do in a signal handler. We should use an FD in the epoll set for signal delivery instead.

**Comment by mattgodbolt** [comment]
Also we use all the wrong signal numbers. QUIT for "shutidown" and "TERM" for "host is going down".

**Comment by snellers** [comment]
Note: if the signals change, they have to change in mudmgr too. I'd left a comment in mudmgr about QUIT being "friendlier". (Incidentally QUIT (3) tells a JVM to dump a stacktrace of all threads.)

**Comment by mattgodbolt** [comment]
Got it. re: mudmgr; might be time to rephrase that a bit. SIGTERM et al is what systemd'll use in the live mud case, but we need something _like_ mudmgr even if it's just purely implemented in Makefile. Right now we dump core on `make stop` which isn't great :P

**Comment by snellers** [comment]
Yeah I noticed that :)

**Comment by mattgodbolt** [comment]
Fixed by c6c1ce60df3e476793847873f200cabfdd372abf
