### ISSUE TITLE
Room 2160 in Gangland lacks the western exit found in the description

### ISSUE THREAD

**Issue by abraidotti** [mattgodbolt/xania#171]
![image](https://user-images.githubusercontent.com/20328440/91051761-8d128600-e5ee-11ea-9cdb-048c5f02a768.png)

**Comment by snellers** [comment]
I looked at this. It looks like it was intended to be a second entrance into gangland, perhaps from slightly further south in Midgaard.  Rather than adding that connection, I'm  going to close it off by changing the description.
