### ISSUE TITLE
Thalos should connect to Juargan

### ISSUE THREAD

**Issue by abraidotti** [mattgodbolt/xania#187]
![image](https://user-images.githubusercontent.com/20328440/91640504-0c87c700-e9ec-11ea-9114-7b9fbf89f53f.png)

No south exit in this room, but a south exit is listed in the description.

**Comment by snellers** [comment]
This room (5281) should connect to room 4774 in Kingdom of Juargan, an old merc area that is currently not in the mud. The reverse exit goes back to room 5279, which seems to be a mistake.  Before Juargan can be connected we need to analyze the mob/object stats. Its possible they are way out of whack. So I'll repurpose this issue for looking at that zone.

**Comment by snellers** [comment]
Added with connections to Thalos (original, not New or Old Thalos) and Moria.  And has a connection to another reinstated old area, Fire Newt Mountain (#162).
