### ISSUE TITLE
re: casting "identify" on container

### ISSUE THREAD

**Issue by abraidotti** [mattgodbolt/xania#190]
![image](https://user-images.githubusercontent.com/20328440/91642901-12d26f00-e9fd-11ea-9da6-8d345823073f.png)

It would be cool if players could get a container's max carry weight by casting "identify" on it.

Maybe the same with drink containers -- it would report the amount of drinks left.

**Comment by snellers** [comment]
4c25d37  adds the total capacity of containers and liquid containers to Lore & Identify.
