### ISSUE TITLE
cast 'disp m' doesn't map to 'dispel magic'

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/xania#194]
Maybe it never did, but perhaps it got broken with the `matches()` changes.

**Comment by snellers** [comment]
None of the two-part spell names did this worked because do_cast relies `skill_lookup` which uses  `!strcmp`. But I have a change I'm trying out...

**Comment by snellers** [comment]
Same with 'acid blast'. With the fix, you can do  c 'a b' self
