### ISSUE TITLE
Add the spell %age next to mana cost

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/xania#202]
Wandera suggests this.

```
Level  1: magic missile        15 mana  ventriloquate         5 mana  
Level  2: detect magic          5 mana  
Level  3: detect invis          5 mana  
Level  4: chill touch          15 mana  
```

to
```
Level  1: magic missile        15 mana    1% ventriloquate         5 mana  100%
Level  2: detect magic          5 mana  100%
Level  3: detect invis          5 mana  100%
Level  4: chill touch          15 mana   97%
```

we need to have room for 2 times ' abc%' chars = 10 more chars on the row. I _think_ that takes us up to 79 characters, so it does fit!

**Comment by abraidotti** [comment]
I like it! It's currently missing the percent sign though:
![image](https://user-images.githubusercontent.com/20328440/91909650-9d280680-ec7b-11ea-8d22-0cb613fbc413.png)
