### ISSUE TITLE
Behaviour change `c word` no longer casts "word of recall"

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/xania#203]
Probably related to the fix for #194 - now `c word` says "you don't know any spells of that name" to Belgarath. On Moog I get "word of divine power".

**Comment by snellers** [comment]
yeah you'd have to use c 'w r' :)

**Comment by mattgodbolt** [comment]
We should collate a list of useful shortcuts, and see if there's a general principal at play here. And/or add specific aliases. At least, perhaps enshrine in tests some more commonly used abbreviations :)

**Comment by mattgodbolt** [comment]
This was fixed by the revert in 65a0c50717d0a83634c0f77bfd5721a9ed079c94
