### ISSUE TITLE
"finger" command and its help and error messages

### ISSUE THREAD

**Issue by abraidotti** [mattgodbolt/xania#205]
![image](https://user-images.githubusercontent.com/20328440/91910387-f04e8900-ec7c-11ea-8c25-769511a28de8.png)

A few things here:

- As a mortal and not a clan leader, I probably shouldn't be able to see this help file (--e.g. if I type "help smite" it says "No help on that word")
- And I probably shouldn't get access to the command, right?
- And the message I get for using it on an existing character is incorrect ;)

**Comment by snellers** [comment]
Finger can be used by anyone. There's a bug in the name matching due to recent tweaks.
