### ISSUE TITLE
Time shown in prompt isn't correct

### ISSUE THREAD

**Issue by pierrewery** [mattgodbolt/xania#217]
When using time in the prompt, it is 1 hour earlier than current time in the UK. Help on the timezone command says the default is British time with BST taken into account.

**Comment by mattgodbolt** [comment]
Right, the time is really UTC. But we should fix up timezones more generally. #95

**Comment by pierrewery** [comment]
Yes. Is the timezone command meant to be for the time in the prompt or does it have another use?

**Comment by snellers** [comment]
@pierrewery  I've "fixed" this by simplifying Xania to only display times in UTC. The 'timezone' command no longer exists and help time mentions UTC too.

**Comment by pierrewery** [comment]
Ok sounds good.
