### ISSUE TITLE
mirror.are beastly fido damage

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/xania#219]
The mirror.are beastly fido:

https://github.com/mattgodbolt/xania/blob/5a7bd54958aeae3ac744e5429bbc37a8c0501ffe/area/mirror.are#L2392-L2406

has a zero damage (`0d2+0`). It's the only mob in the whole mud with no damage. Not sure this was intentional?

**Comment by snellers** [comment]
Strange. Line 2402 shows his damage as `1d2+0`.  This mob is pretty useless, especially taken in context of Old Thalos.  I'm giving it the same stats as the mutant fido from mob factory.  Hunch: it may have been a test mob for `spec_fido`.
