### ISSUE TITLE
Unable to run initial 'make' upon fresh clone of repo:

### ISSUE THREAD

**Issue by Thridi** [mattgodbolt/xania#224]
Following is the complete output after fresh clone:
* git clone
* make
cd /home/mordist/xania/cmake-build-debug && /usr/bin/cmake ..  -DCMAKE_BUILD_TYPE=debug -DCMAKE_INSTALL_PREFIX=/home/mordist/xania/install
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
make[1]: Entering directory '/home/mordist/xania'
Installing conda locally...
/usr/bin/curl -sL --fail -m 120 --connect-timeout 3 --retry 3 --retry-max-time 360 https://repo.anaconda.com/miniconda/Miniconda3-py38_4.8.3-Linux-x86_64.sh -o /home/mordist/xania/.tools/conda-4.8.3/installer.sh
/home/mordist/xania/.tools/conda-4.8.3/installer.sh -u -b -p /home/mordist/xania/.tools/conda-4.8.3
PREFIX=/home/mordist/xania/.tools/conda-4.8.3
Unpacking payload ...
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done

Package Plan ##

  environment location: /home/mordist/xania/.tools/conda-4.8.3

  added / updated specs:
    - _libgcc_mutex==0.1=main
    - ca-certificates==2020.1.1=0
    - certifi==2020.4.5.1=py38_0
    - cffi==1.14.0=py38he30daa8_1
    - chardet==3.0.4=py38_1003
    - conda-package-handling==1.6.1=py38h7b6447c_0
    - conda==4.8.3=py38_0
    - cryptography==2.9.2=py38h1ba5d50_0
    - idna==2.9=py_1
    - ld_impl_linux-64==2.33.1=h53a641e_7
    - libedit==3.1.20181209=hc058e9b_0
    - libffi==3.3=he6710b0_1
    - libgcc-ng==9.1.0=hdf63c60_0
    - libstdcxx-ng==9.1.0=hdf63c60_0
    - ncurses==6.2=he6710b0_1
    - openssl==1.1.1g=h7b6447c_0
    - pip==20.0.2=py38_3
    - pycosat==0.6.3=py38h7b6447c_1
    - pycparser==2.20=py_0
    - pyopenssl==19.1.0=py38_0
    - pysocks==1.7.1=py38_0
    - python==3.8.3=hcff3b4d_0
    - readline==8.0=h7b6447c_0
    - requests==2.23.0=py38_0
    - ruamel_yaml==0.15.87=py38h7b6447c_0
    - setuptools==46.4.0=py38_0
    - six==1.14.0=py38_0
    - sqlite==3.31.1=h62c20be_1
    - tk==8.6.8=hbc83047_0
    - tqdm==4.46.0=py_0
    - urllib3==1.25.8=py38_0
    - wheel==0.34.2=py38_0
    - xz==5.2.5=h7b6447c_0
    - yaml==0.1.7=had09818_2
    - zlib==1.2.11=h7b6447c_3

The following NEW packages will be INSTALLED:

  _libgcc_mutex      pkgs/main/linux-64::_libgcc_mutex-0.1-main
  ca-certificates    pkgs/main/linux-64::ca-certificates-2020.1.1-0
  certifi            pkgs/main/linux-64::certifi-2020.4.5.1-py38_0
  cffi               pkgs/main/linux-64::cffi-1.14.0-py38he30daa8_1
  chardet            pkgs/main/linux-64::chardet-3.0.4-py38_1003
  conda              pkgs/main/linux-64::conda-4.8.3-py38_0
  conda-package-han~ pkgs/main/linux-64::conda-package-handling-1.6.1-py38h7b6447c_0
  cryptography       pkgs/main/linux-64::cryptography-2.9.2-py38h1ba5d50_0
  idna               pkgs/main/noarch::idna-2.9-py_1
  ld_impl_linux-64   pkgs/main/linux-64::ld_impl_linux-64-2.33.1-h53a641e_7
  libedit            pkgs/main/linux-64::libedit-3.1.20181209-hc058e9b_0
  libffi             pkgs/main/linux-64::libffi-3.3-he6710b0_1
  libgcc-ng          pkgs/main/linux-64::libgcc-ng-9.1.0-hdf63c60_0
  libstdcxx-ng       pkgs/main/linux-64::libstdcxx-ng-9.1.0-hdf63c60_0
  ncurses            pkgs/main/linux-64::ncurses-6.2-he6710b0_1
  openssl            pkgs/main/linux-64::openssl-1.1.1g-h7b6447c_0
  pip                pkgs/main/linux-64::pip-20.0.2-py38_3
  pycosat            pkgs/main/linux-64::pycosat-0.6.3-py38h7b6447c_1
  pycparser          pkgs/main/noarch::pycparser-2.20-py_0
  pyopenssl          pkgs/main/linux-64::pyopenssl-19.1.0-py38_0
  pysocks            pkgs/main/linux-64::pysocks-1.7.1-py38_0
  python             pkgs/main/linux-64::python-3.8.3-hcff3b4d_0
  readline           pkgs/main/linux-64::readline-8.0-h7b6447c_0
  requests           pkgs/main/linux-64::requests-2.23.0-py38_0
  ruamel_yaml        pkgs/main/linux-64::ruamel_yaml-0.15.87-py38h7b6447c_0
  setuptools         pkgs/main/linux-64::setuptools-46.4.0-py38_0
  six                pkgs/main/linux-64::six-1.14.0-py38_0
  sqlite             pkgs/main/linux-64::sqlite-3.31.1-h62c20be_1
  tk                 pkgs/main/linux-64::tk-8.6.8-hbc83047_0
  tqdm               pkgs/main/noarch::tqdm-4.46.0-py_0
  urllib3            pkgs/main/linux-64::urllib3-1.25.8-py38_0
  wheel              pkgs/main/linux-64::wheel-0.34.2-py38_0
  xz                 pkgs/main/linux-64::xz-5.2.5-h7b6447c_0
  yaml               pkgs/main/linux-64::yaml-0.1.7-had09818_2
  zlib               pkgs/main/linux-64::zlib-1.2.11-h7b6447c_3

Preparing transaction: ...working... done
Executing transaction: ...working... done
installation finished.
Installing conan locally...
/home/mordist/xania/.tools/conda-4.8.3/bin/pip install conan==1.27.1
Processing /home/mordist/.cache/pip/wheels/68/6d/3f/4c09c257be3c85248385d21f63bb79f8d8c1eccbe20f889edd/conan-1.27.1-py3-none-any.whl
Requirement already satisfied: urllib3!=1.25.4,!=1.25.5 in ./.tools/conda-4.8.3/lib/python3.8/site-packages (from conan==1.27.1) (1.25.8)
Collecting deprecation<2.1,>=2.0
  Using cached deprecation-2.0.7-py2.py3-none-any.whl (11 kB)
Requirement already satisfied: requests<3.0.0,>=2.8.1 in ./.tools/conda-4.8.3/lib/python3.8/site-packages (from conan==1.27.1) (2.23.0)
Processing /home/mordist/.cache/pip/wheels/8e/70/28/3d6ccd6e315f65f245da085482a2e1c7d14b90b30f239e2cf4/future-0.18.2-py3-none-any.whl
Processing /home/mordist/.cache/pip/wheels/ba/28/ae/2185d43c2960e77cd5db53097630625ca1ea502f2ea668373d/pluginbase-0.7-py3-none-any.whl
Processing /home/mordist/.cache/pip/wheels/13/90/db/290ab3a34f2ef0b5a0f89235dc2d40fea83e77de84ed2dc05c/PyYAML-5.3.1-cp38-cp38-linux_x86_64.whl
Collecting bottle<0.13,>=0.12.8
  Using cached bottle-0.12.18-py3-none-any.whl (89 kB)
Collecting fasteners>=0.14.1
  Using cached fasteners-0.15-py2.py3-none-any.whl (23 kB)
Requirement already satisfied: tqdm<5,>=4.28.1 in ./.tools/conda-4.8.3/lib/python3.8/site-packages (from conan==1.27.1) (4.46.0)
Collecting node-semver==0.6.1
  Using cached node_semver-0.6.1-py3-none-any.whl (10 kB)
Collecting distro<1.2.0,>=1.0.2
  Using cached distro-1.1.0-py2.py3-none-any.whl (16 kB)
Collecting Jinja2<3,>=2.3
  Using cached Jinja2-2.11.2-py2.py3-none-any.whl (125 kB)
Collecting python-dateutil<3,>=2.7.0
  Using cached python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Collecting pygments<3.0,>=2.0
  Using cached Pygments-2.7.1-py3-none-any.whl (944 kB)
Collecting colorama<0.5.0,>=0.3.3
  Using cached colorama-0.4.3-py2.py3-none-any.whl (15 kB)
Processing /home/mordist/.cache/pip/wheels/3e/7d/0c/8b312f72847c8301f68a74eba1379133509a9ef17f26b62cc8/patch_ng-1.17.4-py3-none-any.whl
Collecting PyJWT<2.0.0,>=1.4.0
  Using cached PyJWT-1.7.1-py2.py3-none-any.whl (18 kB)
Requirement already satisfied: six<=1.14.0,>=1.10.0 in ./.tools/conda-4.8.3/lib/python3.8/site-packages (from conan==1.27.1) (1.14.0)
Collecting packaging
  Using cached packaging-20.4-py2.py3-none-any.whl (37 kB)
Requirement already satisfied: certifi>=2017.4.17 in ./.tools/conda-4.8.3/lib/python3.8/site-packages (from requests<3.0.0,>=2.8.1->conan==1.27.1) (2020.4.5.1)
Requirement already satisfied: chardet<4,>=3.0.2 in ./.tools/conda-4.8.3/lib/python3.8/site-packages (from requests<3.0.0,>=2.8.1->conan==1.27.1) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in ./.tools/conda-4.8.3/lib/python3.8/site-packages (from requests<3.0.0,>=2.8.1->conan==1.27.1) (2.9)
Collecting monotonic>=0.1
  Using cached monotonic-1.5-py2.py3-none-any.whl (5.3 kB)
Collecting MarkupSafe>=0.23
  Using cached MarkupSafe-1.1.1-cp38-cp38-manylinux1_x86_64.whl (32 kB)
Collecting pyparsing>=2.0.2
  Using cached pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
Installing collected packages: pyparsing, packaging, deprecation, future, pluginbase, PyYAML, bottle, monotonic, fasteners, node-semver, distro, MarkupSafe, Jinja2, python-dateutil, pygments, colorama, patch-ng, PyJWT, conan
Successfully installed Jinja2-2.11.2 MarkupSafe-1.1.1 PyJWT-1.7.1 PyYAML-5.3.1 bottle-0.12.18 colorama-0.4.3 conan-1.27.1 deprecation-2.0.7 distro-1.1.0 fasteners-0.15 future-0.18.2 monotonic-1.5 node-semver-0.6.1 packaging-20.4 patch-ng-1.17.4 pluginbase-0.7 pygments-2.7.1 pyparsing-2.4.7 python-dateutil-2.8.1
Installing clang format static binary locally...
/usr/bin/curl -sL --fail -m 120 --connect-timeout 3 --retry 3 --retry-max-time 360 https://github.com/muttleyxd/clang-format-static-binaries/releases/download/master-5b56bb49/clang-format-10_linux-amd64 -o /home/mordist/xania/.tools/clang-format-10
make[1]: Leaving directory '/home/mordist/xania'
-- Conan: checking conan executable
-- Conan: Found program /home/mordist/xania/.tools/conda-4.8.3/bin/conan
-- Conan: Version found Conan version 1.27.1

-- Conan: checking conan executable
-- Conan: Found program /home/mordist/xania/.tools/conda-4.8.3/bin/conan
-- Conan: Version found Conan version 1.27.1

-- Conan: Adding bincrafters remote repository (https://api.bintray.com/conan/bincrafters/public-conan)
-- Conan: Automatic detection of conan settings from cmake
-- Conan: Settings= -s;build_type=Debug;-s;compiler=gcc;-s;compiler.version=9;-s;compiler.libcxx=libstdc++11
-- Conan: checking conan executable
-- Conan: Found program /home/mordist/xania/.tools/conda-4.8.3/bin/conan
-- Conan: Version found Conan version 1.27.1

-- Conan executing: /home/mordist/xania/.tools/conda-4.8.3/bin/conan install /home/mordist/xania/conanfile.txt -s build_type=Debug -s compiler=gcc -s compiler.version=9 -s compiler.libcxx=libstdc++11 -g=cmake --build=missing
ERROR: compiler not defined for compiler.libcxx
Please define compiler value first too
CMake Error at scripts/conan.cmake:404 (message):
  Conan install failed='1'
Call Stack (most recent call first):
  scripts/conan.cmake:499 (conan_cmake_install)
  CMakeLists.txt:36 (conan_cmake_run)

-- Configuring incomplete, errors occurred!
See also "/home/mordist/xania/cmake-build-debug/CMakeFiles/CMakeOutput.log".
make: *** [Makefile:104: /home/mordist/xania/cmake-build-debug/CMakeCache.txt] Error 1

**Comment by mattgodbolt** [comment]
Thanks! I wonder what's going on there. Looks like conan hasn't been able to find a compiler on your system. What does `which gcc` and `which `g++` say?

**Comment by Thridi** [comment]
mordist@DESKTOP-CNH72VO:~/xania$ which gcc
/usr/bin/gcc
mordist@DESKTOP-CNH72VO:~/xania$ which g++
/usr/bin/g++

**Comment by snellers** [comment]
Just out of interest, do you have a pre-existing custom setup for conan, created for another project? i.e. in ~/.conan/profiles or conan.conf ? I found one or two threads mentioning similar errors, and the workaround was to set up a profile.

**Comment by Thridi** [comment]
Well I initially was able to build, made some code changes and deleted the cloned repo. When I re-cloned the repo and tried to compile I got these errors. So yes there is a profile which was created the first time I cloned the repo. I'll try removing the profile and starting from scratch.

**Comment by Thridi** [comment]
That was it. Everything ran as expected after I removed the ~/.conan directory. Not sure why this would happen as the only time I have ever used conan is with this repo, so why would it fail on a second build.
