### ISSUE TITLE
practice "spell name"

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/xania#226]
is painful:
```
> prac prot good
You can't practice that.
> prac protection good
You practice protection good.
```

Related to our other spell name changes so maybe not useful...

**Comment by snellers** [comment]
I looked into it. The argument parsing for practice is the same as `cast` and some other commands in that it will peel off the first argument and use that to look up the spell.  I'm reluctant to change that behaviour. For a long time, it was necessary to use a quote to denote a multi-word argument and that was already mentioned in the help for `cast`. So I've improved the help for `practice` to mention this too.
