### ISSUE TITLE
You can ungroup individuals during combat.

### ISSUE THREAD

**Issue by stridera** [mattgodbolt/xania#299]
During combat, you can remove people from your group.  This means that the last person to hit the mob gets 100% of the credit.

Probably most useful for powerleveling.  Get a high/low level, both attack, remove the high level, and let the low level get the last hit somehow.  High level will take all attacks.

**Comment by snellers** [comment]
Resolved by [5eb5c23](https://github.com/mattgodbolt/xania/commit/5eb5c2321a01b84768992d679e10e8d11f3f6874)
