### ISSUE TITLE
Project no longer works in CLion

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/xania#303]
Since 8db4e70647397c20fc0f87be8a1ffdefe74e8d67 or around then, it's impossible for me to use the project with my default "It Just Works Out of The Box™" guarantee in CLion.

CLion quite reasonably expects the `CMakeLists.txt` in the root directory to be the one and only project. This doesn't have any of the `conan` stuff in it, which I rely on to have hermetic, clear, unambiguous, "just works" builds, and to not require any particular system dependencies.

So, right now, I can't work on the project, without either a change to CLion or "apt install"ing all the dependencies (which I don't want to do).

**Comment by snellers** [comment]
@mattgodbolt  Thanks for trying those changes out with CLion. I too like how things Just Worked via conan. I'm pretty sure I didn't hit any issues with those changes & vscode. I will give your changes a go after they're merged once I get time and will update the vscode configs if they need tweaking.
