### ISSUE TITLE
During character creation, "help [class]" should be available

### ISSUE THREAD

**Issue by abraidotti** [mattgodbolt/xania#45]
(Tajil here)

When creating a new character, a user can get help for the available races, but not the available classes.
Moreover, I see there are class help entries (e.g. "help knight"), but not a general "help class".

**Comment by snellers** [comment]
Yeah it's even worse than that - when you get prompted to choose your class, you can't run a help command. The creation sequence needs to be improved so that you can.

**Comment by snellers** [comment]
@abraidotti  This'll be in the next update, let me know what you think.

**Comment by abraidotti** [comment]
Looks good!
