### ISSUE TITLE
Reply and Tell command quirks

### ISSUE THREAD

**Issue by abraidotti** [mattgodbolt/xania#62]
"Reply" doesn't seem to work in response to a tell.

What do you think if "Tell" without an argument defaulted to the last person who sent you a tell?

"Tell group" would be a nice alias to Grouptell.

**Comment by snellers** [comment]
I use 'gt' to group tell

**Comment by snellers** [comment]
@abraidotti  I'm not sure there's much to do here.  Sending a tell from character A to character B,  character B can then 'reply message' and it works fine for me as far as I can tell.    The only scenario I've seen where reply may stop working is if character A logs off, character B will 'forget' their last tell target. But perhaps there's another edge case you found?
 
I think 'gtell'  or 'gt' are adequate for telling the group.

Somewhat related:  the 'prefix' command can also be used to line up a 'tell someone ...' command, or any other,if you know you're going to be repeating the same command but with different args each time.

**Comment by abraidotti** [comment]
Understood. I don't think I found an edge case; just didn't know the syntax.
