### ISSUE TITLE
Where command could be more useful

### ISSUE THREAD

**Issue by abraidotti** [mattgodbolt/xania#64]
![where](https://user-images.githubusercontent.com/20328440/88861618-581c3a80-d1cc-11ea-8e34-344ee0594f27.png)

Currently, the Where command lists players (including myself) in the same area and the room title.

Listing myself among the players seems buggy.
More helpful would be the first line saying "You are in ==AREA TITLE==" and then displaying the table of other players.
And it would be helpful to list my pet, so I can find it if get separated.

**Comment by snellers** [comment]
@abraidotti  I agree those are nice touches, thanks. It'll be in the next reboot!

**Comment by snellers** [comment]
Incidentally, as pets are NPCs,  passing its name to the where command should also locate it, but that'll no longer be necessary.
