### ISSUE TITLE
Smurfette's tiny key

### ISSUE THREAD

**Issue by abraidotti** [mattgodbolt/xania#68]
I've looked through smurf2.are and I don't think Smurfette's tiny key has a use. Maybe it should open a lockbox or something?

**Comment by snellers** [comment]
@abraidotti  I'm adding a little jewel box to her room that the key will open. It's a useful intro for new players! 

Interestingly, Xania doesn't actually load "smurf2.are", it uses "smurf.are" instead.  Some of the mob HP/damage stats are different in smurf2.are. I'm guessing it's actually a legacy file.  I'm going to delete it from the repo. A long time ago there was an area file format upgrade, and I think smurf2.are (which doesn't have all of the elements present in smurf.are) may have been replaced.
