### ISSUE TITLE
Binary isn't being copied to install/bin directory.

### ISSUE THREAD

**Issue by johnburkhard** [mattgodbolt/xania#7]
When running `make install` the binary isn't copied. Possible to include setup instructions in the README?

**Comment by mattgodbolt** [comment]
In theory just running `make` from the top-level makefile does all the magic needed. We're still working on getting a good interaction between my personal goal of "`make` should just work" and the more advanced stuff using cmake. My personal setup is to run and debug from an IDE (which understands cmake) from the cmake-build-debug, without installing. The install is only there for the "final build". Which now should copy things appropritately as we're now using it to deploy to a running instance (still under test).

Can you double-check and let us know if it looks fixed now? Thanks!

**Comment by mattgodbolt** [comment]
Also we absolutely should have more info in the README! Will make a separate issue for that (so we can close this if the installation thing is fixed?) - #11

**Comment by mattgodbolt** [comment]
I'm hoping this is fixed for you - we've done a lot of hackery to try and make this more stable (and CIs to test it), plus I've updated the README.md. Please feel free to reopen this if you're still stuck or can repro the issue!

Thanks :)
