### ISSUE TITLE
Wolfe Point area quirks

### ISSUE THREAD

**Issue by abraidotti** [mattgodbolt/xania#78]
![image](https://user-images.githubusercontent.com/20328440/89051677-9c215380-d322-11ea-849b-314e3ef68f07.png)

- I'm a wolf cleric but I can enter any guild. Bug?
- pictured: I've entered the mage's guild and it looks like both the cleric and mage guildmaster have spawned here.

**Comment by snellers** [comment]
@abraidotti  I've created a holy shrine east down the street and put the cleric GM there. And entrance to each guild room is now restricted like Midgaard and New Thalos.  Annoyingly, the special status of these rooms isn't configured with a 'room flag' in the area file. Instead, there's a specific bit of code that checks an 'allow list' of guild rooms for each class. Fortunately it's very rare that new class-specific rooms get added.
