### ISSUE TITLE
Blindness spell is missing a failure message.

### ISSUE THREAD

**Issue by abraidotti** [mattgodbolt/xania#79]
When I cast blind on a mob and it fails, or if the mob is already blinded, there's no message telling me that.

**Comment by snellers** [comment]
@abraidotti  In the next update, the blindness spell will say:
- You are already blind.  (If blinding yourself and you are already)
- MobName is already blind. (Sent to the caster of the spell).
- MobName shakes off an attempt to blind him/her/it.  (Sent to the room, if resisted).
