### ISSUE TITLE
Autosplit message when group < 2 

### ISSUE THREAD

**Issue by abraidotti** [mattgodbolt/xania#89]
![image](https://user-images.githubusercontent.com/20328440/89133371-44811480-d4e9-11ea-8673-c1500eb3c3c8.png)

"Just keep it all" seems unnecessary and might confuse players. What do you think?

**Comment by snellers** [comment]
Resolved by  c575c3b59d73

**Comment by snellers** [comment]
Note: the regular "split" command uses this message too if it can't find a player character in the same room. The easiest way to repro the problem is to type split 50 when you have a pet.
