### ISSUE TITLE
timezone command poor parsing

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/xania#95]
`do_timezone` uses sscanf and doesn't check returns so:

```
> timezone Chicago
Time will now be displayed 0: 0 from GMT
> timezone -5
Time will now be displayed -5:-1 from GMT
> timezone -5:0
Time will now be displayed -5: 0 from GMT
```

(while we're at it, actually using named timezones which account for DST would be even better..)

**Comment by snellers** [comment]
I've "fixed" this by simplifying Xania to only display times in UTC. The 'timezone' command no longer exists and help time mentions UTC too.
